dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install -g truffle dotenv
  - npm install

before_script:
  - truffle version

script:
  - npm run lint
  - npm run lint:sol
  - testrpc &> /dev/null &
  - truffle test